# Copyright (c) 2021 Project CHIP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Restyle

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.number) || (github.event_name == 'workflow_dispatch' && github.run_number) || github.sha }}
  cancel-in-progress: true

jobs:
  restyle:
    name: Restyle Check

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Start Restyler
        run: |
          docker create --interactive --rm \
            --name restyler \
            --env LOG_LEVEL \
            --env LOG_DESTINATION \
            --env LOG_FORMAT \
            --env LOG_COLOR \
            --env HOST_DIRECTORY="$PWD" \
            --env UNRESTRICTED=1 \
            --volume "$PWD":/code \
            --volume /tmp:/tmp \
            --volume /var/run/docker.sock:/var/run/docker.sock \
            --entrypoint tail \
            restyled/restyler:edge \
            -f \
            /dev/null
          docker start restyler
          docker inspect --format "{{range .Config.Env}}{{println .}}{{end}}" restyler
      - name: Check Files Changed
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          FILE_LIST=$(git diff $BASE_SHA..$HEAD_SHA --pretty=format:--name-only --ignore-submodules --diff-filter=d)
          echo "Restyling files changed: ($BASE_SHA..$HEAD_SHA)"
          for file in $FILE_LIST; do  echo "  $file";  done
          docker exec restyler restyle-path $FILE_LIST
          git diff --exit-code --no-ext-diff
